Ioni\PayzenBundle\Model\SubscriptionInfos:
    type: embeddable
    fields:
        identifier:
            type: string
            length: 31
            nullable: true
        amount:
            type: integer
            nullable: true
        beginDate:
            type: datetime
            nullable: true
        endDate:
            type: datetime
            nullable: true
        frequency:
            type: string
            length: 15
            nullable: true
        count:
            type: integer
            nullable: true
        monthDay:
            type: integer
            nullable: true
        interval:
            type: integer
            nullable: true
        lastRecurrenceNumber:
            type: integer
            nullable: true
        responses:
            type: json_array
            nullable: true
