Ioni\PayzenBundle\Model\TransactionCustomer:
    type: embeddable
    fields:
        status:
            type: string
            length: 15
        firstname:
            type: string
            length: 63
            nullable: true
        lastname:
            type: string
            length: 63
            nullable: true
        legalName:
            type: string
            length: 100
            nullable: true
        streetNumber:
            type: string
            length: 5
            nullable: true
        address:
            type: string
            length: 255
            nullable: true
        postalCode:
            type: string
            length: 64
            nullable: true
        city:
            type: string
            length: 128
            nullable: true
        state:
            type: string
            length: 127
            nullable: true
        country:
            type: string
            length: 2
            nullable: true
            options:
                fixed: true
        phone:
            type: string
            length: 32
            nullable: true
        customerId:
            type: string
            length: 63
            nullable: true
        title:
            type: string
            length: 63
            nullable: true
        email:
            type: string
            length: 150
            nullable: true
