Ioni\PayzenBundle\Model\Transaction:
    type: entity
    table: ioni_payzen_transaction
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        amount:
            type: integer
            nullable: true
        currency:
            type: string
            length: 3
            options:
                fixed: true
        number:
            type: string
            length: 6
            nullable: true
            options:
                fixed: true
        status:
            type: string
            length: 15
        resultCode:
            type: string
            length: 2
            nullable: true
            options:
                fixed: true
        response:
            type: json_array
            nullable: true
        createdAt:
            type: datetime
        updatedAt:
            type: datetime
    embedded:
        customer:
            class: Ioni\PayzenBundle\Model\TransactionCustomer
        shipping:
            class: Ioni\PayzenBundle\Model\TransactionShipping
        subscriptionInfos:
            class: Ioni\PayzenBundle\Model\SubscriptionInfos
    oneToMany:
        products:
            targetEntity: Ioni\PayzenBundle\Model\TransactionProduct
            mappedBy: transaction
            cascade: ['persist', 'remove']
